# conda env create -f environment.yml
# conda activate nb
name: nb
channels:               
  - anaconda               
  - astropy                 
  - conda-forge          
  - defaults
dependencies:
  - python>=3.9
  - numpy
  - scipy
  - matplotlib
  - ca-certificates
  - certifi
  - openssl
  - emcee
  - astropy
  - corner
  - jupyterlab
  - seaborn
  - ipywidgets
  - specutils
  - vitables
